#!/bin/bash
sudo sed -i's/#PermitRootlogin yes/PermitRootlogin yes/' /etc/ssh/sshd_config
sudo sed -i's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/hd_config
sudo service sshd restart
sudo echo 'root:chanduravi'|chpasswd
hostname MASTER


sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenki.repo
  sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key


  yum install java jenkins -y
  service jenkins start
  service jenkins status
  cat /var/lib/jenkins/secrets/initialAdminPassword

